# Generated by Django 4.0.6 on 2023-05-08 09:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('about_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_year', models.CharField(max_length=500)),
                ('school_name', models.CharField(max_length=1000)),
                ('level', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('work_year', models.CharField(max_length=500)),
                ('worplace_name', models.CharField(max_length=1000)),
                ('role', models.CharField(blank=True, max_length=1000, null=True)),
                ('responsibilities', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('self_caption', models.TextField(null=True)),
                ('self_description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('explore_title', models.CharField(max_length=2000)),
                ('explore_description', models.TextField()),
                ('explore_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('journey_Title', models.CharField(max_length=500)),
                ('journey_Year', models.DateField(blank=True, null=True)),
                ('journey_Description', models.TextField(default='NOT AVAILABLE')),
                ('journey_Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(max_length=500)),
                ('proficiency', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.DateField(blank=True, null=True)),
                ('project_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('project_challenges', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('project_solution', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=2000, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('product_Image', models.FileField(blank=True, null=True, upload_to='')),
                ('project_Tag', models.ManyToManyField(blank=True, to='myPortfolio.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='')),
                ('work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.work')),
            ],
        ),
    ]
